stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git config --global user.email "julionewton98@gmail.com"
    - git config --global user.name "julionewton98"
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/proyecto_salsa.git
    - git push github --all
    - git push github --tags
  only:
    - dev   # change this if your main branch has a different name
