stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git config --global user.email "julionewton98@gmail.com"
    - git config --global user.name "Julio-max4"
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/your-repo.git
    - git push github --all
    - git push github --tags
  only:
    - main   # change this if your main branch has a different name
